@echo off
setlocal

:: Set the current directory to the script's location
cd /d "%~dp0"

call compileAll.bat

:: Name of the benchmark script created previously
set "BENCHMARK_SCRIPT=ExecuteThreadVar.bat"

:: Safety check: verify that the benchmark script exists
if not exist "%BENCHMARK_SCRIPT%" (
    echo Error: The script "%BENCHMARK_SCRIPT%" was not found.
    echo Make sure it is named correctly and located in the same folder.
    pause
    exit /b 1
)

echo Starting automated execution of all benchmarks...
echo.

:: List of all executables generated by the first compilation script
set "EXECUTABLES= MainCodeTrial.exe OptimizedCodeTrial.exe
OptimizedCodeTrialO3.exe UltraOptimizedCodeTrial.exe UltraOptimizedCodeTrialO3.exe"

:: For loop iterating through each executable in the list
for %%E in (%EXECUTABLES%) do (
    echo =======================================================
    echo Starting tests for: %%E
    echo =======================================================

    :: Verify that the executable exists before launching the test
    if exist "%%E" (
        echo [1/2] Executing with target word: tree
        call "%BENCHMARK_SCRIPT%" "%%E" "tree"

        echo.
        echo [2/2] Executing with target word: uneven
        call "%BENCHMARK_SCRIPT%" "%%E" "uneven"
    ) else (
        echo [WARNING] The executable "%%E" does not exist. Did you run the compilation script? Skipping...
    )

    echo.
)

echo.
echo =======================================================
echo All benchmarks have been completed successfully!
echo =======================================================
pause
endlocal